# backend/app/rag/retriever.py
"""Retriever for the RAG system.

This module loads the FAISS index generated by :pymod:`knowledge_loader` and
provides a simple interface to fetch the most relevant markdown chunks for a
given query.
"""

from typing import List, Dict
import numpy as np

from .knowledge_loader import KnowledgeLoader


class Retriever:
    """Retrieve top‑k relevant knowledge chunks using the FAISS vector store."""

    def __init__(self, top_k: int = 5):
        # Load the pre‑built index and metadata
        self.loader = KnowledgeLoader.load_existing()
        self.top_k = top_k

    def retrieve(self, query: str) -> List[Dict[str, str]]:
        """Return the *top_k* most relevant chunks for *query*.

        Parameters
        ----------
        query: str
            The user query or question.

        Returns
        -------
        List[Dict[str, str]]
            A list of dictionaries, each containing ``source`` (file path) and
            ``text`` (the chunk content). The list is ordered from most to least
            relevant.
        """
        if not self.loader.index:
            raise RuntimeError("FAISS index not loaded. Ensure KnowledgeLoader.build() has been called.")
        # Embed the query using the same model
        query_vec = self.loader.embed_query(query)
        # Perform a similarity search (inner product = cosine for normalized vectors)
        distances, indices = self.loader.index.search(query_vec, self.top_k)
        results: List[Dict[str, str]] = []
        for idx in indices[0]:
            meta = self.loader.metadata[idx]
            results.append({"source": meta["source"], "text": meta["text"]})
        return results
